#!/usr/bin/env node

/**
 * Environment Setup Script for LingoQuesto Voice Chat
 * This script helps developers set up their environment variables
 */

import fs from 'fs'
import path from 'path'
import readline from 'readline'
import { fileURLToPath } from 'url'
import { dirname } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

const question = (query) => new Promise((resolve) => rl.question(query, resolve))

async function setupEnvironment() {
  console.log('🚀 LingoQuesto Voice Chat - Environment Setup\n')

  try {
    // Check if .env.local already exists
    const envLocalPath = path.join(process.cwd(), '.env.local')
    if (fs.existsSync(envLocalPath)) {
      const overwrite = await question('.env.local already exists. Overwrite? (y/N): ')
      if (overwrite.toLowerCase() !== 'y') {
        console.log('Setup cancelled.')
        rl.close()
        return
      }
    }

    console.log('Please provide your Supabase credentials:')
    console.log('You can find these in your Supabase Dashboard > Settings > API\n')

    const supabaseUrl = await question('Supabase Project URL: ')
    const supabaseAnonKey = await question('Supabase Anonymous Key: ')

    // Optional configurations
    const maxParticipants = (await question('Max participants per room (default: 20): ')) || '20'
    const defaultLanguage = (await question('Default language (default: en): ')) || 'en'
    const audioQuality = (await question('Audio quality (default: high): ')) || 'high'

    // Create .env.local content
    const envContent = `# Local Development Environment Variables
# Generated by setup-env.js script

# Supabase Configuration
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseAnonKey}

# Voice Chat Settings
VITE_VOICE_CHAT_MAX_PARTICIPANTS=${maxParticipants}
VITE_VOICE_CHAT_DEFAULT_LANGUAGE=${defaultLanguage}
VITE_VOICE_CHAT_AUDIO_QUALITY=${audioQuality}

# Development Settings
VITE_DEV_MODE=true
VITE_ENABLE_LOGGING=true

# IMPORTANT: Never commit this file to version control
`

    // Write .env.local file
    fs.writeFileSync(envLocalPath, envContent)

    console.log('\n✅ Environment configuration created successfully!')
    console.log(`📁 File created: ${envLocalPath}`)
    console.log('\n🔧 Next steps:')
    console.log('1. Verify your Supabase credentials are correct')
    console.log('2. Run the SQL schema in your Supabase Dashboard')
    console.log('3. Enable Realtime for voice_chat_rooms and voice_chat_participants tables')
    console.log('4. Start development server: npm run dev')
    console.log('\n📚 For more information, see VOICE_CHAT_README.md')
  } catch (error) {
    console.error('❌ Error setting up environment:', error.message)
    process.exit(1)
  } finally {
    rl.close()
  }
}

// Validate Supabase URL format
function validateSupabaseUrl(url) {
  const urlPattern = /^https:\/\/[a-zA-Z0-9-]+\.supabase\.co$/
  return urlPattern.test(url)
}

// Validate Supabase key format
function validateSupabaseKey(key) {
  const keyPattern = /^eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+$/
  return keyPattern.test(key)
}

// Run setup
setupEnvironment()
